{
 "title": "Microservices Overview",
 "tags": [ "microservices" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(order_requests_total[1m])", "legendFormat": "Order Service" },
    { "expr": "rate(auth_requests_total[1m])", "legendFormat": "Auth Service" },
    {
     "expr": "rate(payment_requests_total[1m])",
     "legendFormat": "Payment Service"
    }
   ]
  },
  {
   "title": "Service Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "order_errors_total", "legendFormat": "Order Errors" },
    { "expr": "payment_failed_total", "legendFormat": "Payment Failures" }
   ]
  },
  {
   "title": "Services Up/Down Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{job='auth-service'}", "legendFormat": "Auth" },
    { "expr": "up{job='product-service'}", "legendFormat": "Product" },
    { "expr": "up{job='order-service'}", "legendFormat": "Order" },
    { "expr": "up{job='user-service'}", "legendFormat": "User" },
    { "expr": "up{job='payment-service'}", "legendFormat": "Payment" },
    { "expr": "up{job='notification-service'}", "legendFormat": "Notification" }
   ]
  }
 ]
}