#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE authdb;
    CREATE DATABASE productdb;
    CREATE DATABASE orderdb;
    CREATE DATABASE userdb;
    CREATE DATABASE chatdb;
    CREATE DATABASE paymentdb;
    CREATE DATABASE notificationdb;
    GRANT ALL PRIVILEGES ON DATABASE authdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE productdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE orderdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE userdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE chatdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE paymentdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE notificationdb TO "$POSTGRES_USER";
EOSQL